### ISSUE TITLE
Width and height not set in PHPCR Image

### ISSUE THREAD

**Issue by danielanteloagra** [symfony-cmf/MediaBundle#126]
Are width and height meant to be manually populated or should they be self calculated on "copyContentFromFile"?

e.g.

```
use Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\Image;
use Symfony\Component\HttpFoundation\File\UploadedFile;

$uploadedImage = new UploadedFile($imgPath, 'test.jpg', 'image/jpeg', null, null, true);
$image = new Image();
$image->copyContentFromFile($uploadedImage);

// Failed asserting that 0 matches expected '500'.
$this->assertEquals('500', $image->getWidth()); 
```

**Comment by dbu** [comment]
this happens in a [doctrine subscriber](https://github.com/symfony-cmf/MediaBundle/blob/master/Doctrine/DoctrineImageDimensionsSubscriber.php) but only when the document is written - there is no event system inside the image document, and we don't want to inject Imagine or GD into the Image class.

that event listener should be [enabled by default](http://symfony.com/doc/master/cmf/bundles/media/configuration.html#event-listeners-image-dimension)

does your test work if you persist and flush $image before checking the image width?
