### ISSUE TITLE
use MediaBundle twig functions

### ISSUE THREAD

**Issue by elenitaex5** [symfony-cmf/MediaBundle#140]
Hi, I'm trying to use MediaBundle in my twig template in a image gallery.

I've this:
\< a href="{{ cmf_media_download_url(XXX) }}" title="Download" \>Download\</a\>

but it throws me a TWIG error:
"The function "cmf_media_download_url" does not exist in XXXBundle::XXX.html.twig "

of course i have in my:
 app/config/routing.yml
![image](https://cloud.githubusercontent.com/assets/14013852/9656418/7a0247c0-5238-11e5-8866-8845cbef2e66.png)

app/AppKernel.php
![image](https://cloud.githubusercontent.com/assets/14013852/9656437/93cd80c0-5238-11e5-83c3-89ad3038177b.png)

could anybody help me?

**Comment by dbu** [comment]
this is only available with phpcr-odm. you need to enable phpcr for this bundle to have the twig extension loaded.

If you want to use ORM, you would need to look into the twig extension and see if you can adjust it to also work with Doctrine ORM. A pull request to make that possible would be great - ORM support for the twig helpers is something we want but nobody had time to build it.

see also http://stackoverflow.com/questions/31919763/symfony-cmf-media-bundle-could-not-load-type-cmf-media-image for similar discussion about the form types.
