### ISSUE TITLE
Can we use S3DataStore with Jackrabbit implementation for media bundle?

### ISSUE THREAD

**Issue by steffenbrem** [symfony-cmf/MediaBundle#147]
I've read that you can store the blobs on a separate system (such as Amazon S3) with data stores. I know that Oak supports it, but I also saw that Jackrabbit 2.8 had support for it (https://jackrabbit.apache.org/api/2.8/org/apache/jackrabbit/aws/ext/ds/S3DataStore.html). Anyone here implemented something like this with the MediaBundle? Is it possible to achieve S3 storage with latest Jackrabbit 2.x?

**Comment by dbu** [comment]
i would not know of it, sorry. but maybe you have more chances to find
somebody who did that when asking on the jackrabbit mailinglist, as this
question is not specific to the cmf or even the php client in general.

**Comment by steffenbrem** [comment]
@dbu Do you think it is a good idea to use the `Jackrabbit Amazon WebServices Extension` in conjunction with the `MediaBundle` to achieve proper `CDN` and scalable files etc. I have looked at using the SonataMediaBundle, but I don't think that is a good fit for this. It is important for me that the binaries are scalable and can be provided from multiple locations (I use S3 + CloudFront for this). Right now I think using plain `MediaBundle` and implement the `S3DataStore` in my Jackrabbit repository is the best way to go, is this true?
